version: "3.2"
services:
  redis:
    image: "redis:5.0-alpine"
    command: redis-server
    volumes:
      - "./tmp/redis:/var/lib/redis/data"
    networks:
      net:
        ipv4_address: 172.18.1.1
  tapyrus1:
    build: ./core
    networks:
      net:
        ipv4_address: 172.18.2.1
    tty: true
    volumes:
      - ./tmp/tapyrus1:/var/lib/tapyrus
      - ./core/genesis.1905960821:/var/lib/tapyrus/genesis.1905960821
      - ./core/tapyrus1.conf:/var/lib/tapyrus/tapyrus.conf
  tapyrus2:
    build: ./core
    networks:
      net:
        ipv4_address: 172.18.2.2
    tty: true
    volumes:
      - ./tmp/tapyrus2:/var/lib/tapyrus
      - ./core/genesis.1905960821:/var/lib/tapyrus/genesis.1905960821
      - ./core/tapyrus2.conf:/var/lib/tapyrus/tapyrus.conf
  tapyrus3:
    build: ./core
    networks:
      net:
        ipv4_address: 172.18.2.3
    tty: true
    volumes:
      - ./tmp/tapyrus3:/var/lib/tapyrus
      - ./core/genesis.1905960821:/var/lib/tapyrus/genesis.1905960821
      - ./core/tapyrus3.conf:/var/lib/tapyrus/tapyrus.conf
  tapyrus4:
    build: ./core
    networks:
      net:
        ipv4_address: 172.18.2.4
    tty: true
    volumes:
      - ./tmp/tapyrus4:/var/lib/tapyrus
      - ./core/genesis.1905960821:/var/lib/tapyrus/genesis.1905960821
      - ./core/tapyrus4.conf:/var/lib/tapyrus/tapyrus.conf
  signer1:
    build: ./signer
    command:
      [
        "/tmp/run.sh",
        "-c",
        "/tmp/signer1.toml",
        "--skip-waiting-ibd",
      ]
    entrypoint:
      [
        "prehook",
        "dockerize -wait tcp://tapyrus1:12381 -wait tcp://redis:6379 -timeout 60s",
        "--",
      ]
    networks:
      net:
        ipv4_address: 172.18.3.1
    volumes:
      - ./tmp/signer1:/tmp
      - type: bind
        source: ./signer/run.sh
        target: /tmp/run.sh
      - type: bind
        source: ./signer/signer1.toml
        target: /tmp/signer1.toml
      - type: bind
        source: ./signer/federations1.toml
        target: /tmp/federations1.toml
  signer2:
    build: ./signer
    command:
      [
        "/tmp/run.sh",
        "-c=/tmp/signer2.toml",
        "--skip-waiting-ibd",
      ]
    entrypoint:
      [
        "prehook",
        "dockerize -wait tcp://tapyrus2:12381 -wait tcp://redis:6379 -timeout 60s",
        "--",
      ]
    networks:
      net:
        ipv4_address: 172.18.3.2
    volumes:
      - ./tmp/signer2:/tmp
      - type: bind
        source: ./signer/run.sh
        target: /tmp/run.sh
      - type: bind
        source: ./signer/signer2.toml
        target: /tmp/signer2.toml
      - type: bind
        source: ./signer/federations2.toml
        target: /tmp/federations2.toml
  signer3:
    build: ./signer
    command:
      [
        "/tmp/run.sh",
        "-c=/tmp/signer3.toml",
        "--skip-waiting-ibd",
      ]
    entrypoint:
      [
        "prehook",
        "dockerize -wait tcp://tapyrus3:12381 -wait tcp://redis:6379 -timeout 60s",
        "--",
      ]
    networks:
      net:
        ipv4_address: 172.18.3.3
    volumes:
      - ./tmp/signer3:/tmp/
      - type: bind
        source: ./signer/run.sh
        target: /tmp/run.sh
      - type: bind
        source: ./signer/signer3.toml
        target: /tmp/signer3.toml
      - type: bind
        source: ./signer/federations3.toml
        target: /tmp/federations3.toml
  signer4:
    build: ./signer
    command:
      [
        "/tmp/run.sh",
        "-c=/tmp/signer4.toml",
        "--skip-waiting-ibd",
      ]
    entrypoint:
      [
        "prehook",
        "dockerize -wait tcp://tapyrus3:12381 -wait tcp://redis:6379 -timeout 60s",
        "--",
      ]
    networks:
      net:
        ipv4_address: 172.18.3.4
    volumes:
      - ./tmp/signer4:/tmp/
      - type: bind
        source: ./signer/run.sh
        target: /tmp/run.sh
      - type: bind
        source: ./signer/signer4.toml
        target: /tmp/signer4.toml
      - type: bind
        source: ./signer/federations4.toml
        target: /tmp/federations4.toml
  electrs1:
    build: ./electrs
    command:
      [
        "/tmp/scripts/run.sh",
        "-vvvv",
        "--timestamp",
        "--db-dir",
        "/root/db",
        "--daemon-dir",
        "/root/.bitcoin/prod-1905960821",
        "--network",
        "prod",
        "--network-id",
        "1905960821",
        "--electrum-rpc-addr",
        "0.0.0.0:50001",
        "--daemon-rpc-addr",
        "tapyrus1:12381",
        "--txid-limit",
        "0",
      ]
    networks:
      net:
        ipv4_address: 172.18.4.1
    tty: true
    volumes:
      - ./electrs/run.sh:/tmp/scripts/run.sh
      - ./tmp/electrs1/log:/tmp/log
      - ./tmp/electrs1/db:/root/db
      - ./tmp/tapyrus1:/root/.bitcoin
      - ./electrs/.cookie:/root/.bitcoin/prod-1905960821/.cookie
  client:
    build: ./client
    entrypoint: ["tail", "-f", "/dev/null"]
    networks:
      net:
        ipv4_address: 172.18.5.1
networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
volumes:
  redis:
    driver: local
  tapyrus1:
    driver: local
  tapyrus2:
    driver: local
  tapyrus3:
    driver: local
  tapyrus4:
    driver: local
  signer1:
    driver: local
  signer2:
    driver: local
  signer3:
    driver: local
  signer4:
    driver: local
  electrs1:
    driver: local
  client:
    driver: local
