version: "3.2"
services:
  redis:
    image: "redis:5.0-alpine"
    command: redis-server
    volumes:
      - "./tmp/redis:/var/lib/redis/data"
    networks:
      net:
        ipv4_address: 172.18.1.1
  tapyrus1:
    build: ./core
    networks:
      net:
        ipv4_address: 172.18.2.1
    tty: true
    volumes:
      - ./tmp/tapyrus1:/var/lib/tapyrus
      - ./core/genesis.dat:/var/lib/tapyrus/genesis.dat
      - ./core/tapyrus1.conf:/var/lib/tapyrus/tapyrus.conf
  tapyrus2:
    build: ./core
    networks:
      net:
        ipv4_address: 172.18.2.2
    tty: true
    volumes:
      - ./tmp/tapyrus2:/var/lib/tapyrus
      - ./core/genesis.dat:/var/lib/tapyrus/genesis.dat
      - ./core/tapyrus2.conf:/var/lib/tapyrus/tapyrus.conf
  tapyrus3:
    build: ./core
    networks:
      net:
        ipv4_address: 172.18.2.3
    tty: true
    volumes:
      - ./tmp/tapyrus3:/var/lib/tapyrus
      - ./core/genesis.dat:/var/lib/tapyrus/genesis.dat
      - ./core/tapyrus3.conf:/var/lib/tapyrus/tapyrus.conf
  signer1:
    build: ./signer
    command:
      [
        "/tmp/run.sh",
        "-p=03842d51608d08bee79587fb3b54ea68f5279e13fac7d72515a7205e6672858ca2",
        "-p=03e568e3a5641ac21930b51f92fb6dd201fb46faae560b108cf3a96380da08dee1",
        "-p=02a1c8965ed06987fa6d7e0f552db707065352283ab3c1471510b12a76a5905287",
        "--privatekey=cQyv2tNYfsRbX8AeAVmeKqzdrv8f2P8LibtbYUPoEu7tJ2rn3NVW",
        "--to_address=mzfmVfHKh4KtUUorQRYnHpHNDWNtKJ5iBf",
        "-t",
        "2",
        "--rpchost=tapyrus1",
        "--rpcport=12381",
        "--rpcuser=user",
        "--rpcpass=pass",
        "--redishost=redis",
        "--log=debug",
        "--skip-waiting-ibd",
      ]
    entrypoint:
      [
        "prehook",
        "dockerize -wait tcp://tapyrus1:12381 -wait tcp://redis:6379 -timeout 60s",
        "--",
      ]
    networks:
      net:
        ipv4_address: 172.18.3.1
    volumes:
      - ./tmp/signer1:/tmp/log
      - type: bind
        source: ./signer/run.sh
        target: /tmp/run.sh
  signer2:
    build: ./signer
    command:
      [
        "/tmp/run.sh",
        "-p=03842d51608d08bee79587fb3b54ea68f5279e13fac7d72515a7205e6672858ca2",
        "-p=03e568e3a5641ac21930b51f92fb6dd201fb46faae560b108cf3a96380da08dee1",
        "-p=02a1c8965ed06987fa6d7e0f552db707065352283ab3c1471510b12a76a5905287",
        "--privatekey=cQYYBMFS9dRR3Mt16gW4jixCqSiMhCwuDMHUBs6WeHMTxMnsq8Gh",
        "--to_address=mpWsEZecvXeYEo2n9oPNGrbpHaY54KaUUL",
        "-t",
        "2",
        "--rpchost=tapyrus2",
        "--rpcport=12381",
        "--rpcuser=user",
        "--rpcpass=pass",
        "--redishost=redis",
        "--log=debug",
        "--skip-waiting-ibd",
      ]
    entrypoint:
      [
        "prehook",
        "dockerize -wait tcp://tapyrus2:12381 -wait tcp://redis:6379 -timeout 60s",
        "--",
      ]
    networks:
      net:
        ipv4_address: 172.18.3.2
    volumes:
      - ./tmp/signer2:/tmp/log
      - type: bind
        source: ./signer/run.sh
        target: /tmp/run.sh

  signer3:
    build: ./signer
    command:
      [
        "/tmp/run.sh",
        "-p=03842d51608d08bee79587fb3b54ea68f5279e13fac7d72515a7205e6672858ca2",
        "-p=03e568e3a5641ac21930b51f92fb6dd201fb46faae560b108cf3a96380da08dee1",
        "-p=02a1c8965ed06987fa6d7e0f552db707065352283ab3c1471510b12a76a5905287",
        "--privatekey=cTGpijFpMsDNA6qXXPh2cuUdGNbsjd5TtjTEp71TkzVvcizzsydm",
        "--to_address=mpCaDciCh3oSPEgeQ5dvkN8q9gdQGC63nb",
        "-t",
        "2",
        "--rpchost=tapyrus3",
        "--rpcport=12381",
        "--rpcuser=user",
        "--rpcpass=pass",
        "--redishost=redis",
        "--log=debug",
        "--skip-waiting-ibd",
      ]
    entrypoint:
      [
        "prehook",
        "dockerize -wait tcp://tapyrus3:12381 -wait tcp://redis:6379 -timeout 60s",
        "--",
      ]
    networks:
      net:
        ipv4_address: 172.18.3.3
    volumes:
      - ./tmp/signer3:/tmp/log
      - type: bind
        source: ./signer/run.sh
        target: /tmp/run.sh
  electrs1:
    build: ./electrs
    command:
      [
        "/tmp/scripts/run.sh",
        "-vvvv",
        "--timestamp",
        "--db-dir",
        "/root/db",
        "--electrum-rpc-addr",
        "0.0.0.0:50001",
        "--network",
        "regtest",
        "--daemon-rpc-addr",
        "tapyrus1:12381",
        "--txid-limit",
        "0",
      ]
    networks:
      net:
        ipv4_address: 172.18.4.1
    tty: true
    volumes:
      - ./electrs/run.sh:/tmp/scripts/run.sh
      - ./tmp/electrs1/log:/tmp/log
      - ./tmp/electrs1/db:/root/db
      - ./tmp/tapyrus1:/root/.bitcoin
      - ./electrs/.cookie:/root/.bitcoin/regtest/.cookie
  client:
    build: ./client
    entrypoint: ["tail", "-f", "/dev/null"]
    networks:
      net:
        ipv4_address: 172.18.5.1
networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
volumes:
  redis:
    driver: local
  tapyrus1:
    driver: local
  tapyrus2:
    driver: local
  tapyrus3:
    driver: local
  signer1:
    driver: local
  signer2:
    driver: local
  signer3:
    driver: local
  electrs1:
    driver: local
  client:
    driver: local
