[signer]
to-address = "16ULVva73ZhQiZu9o3njXc3TZ3aSog7FQQ"
public-key = "03b8ad9e3271a20d5eb2b622e455fcffa5c9c90e38b192772b2e1b58f6b442e78d"
federations-file = "/tmp/federations1.toml"

[rpc]
rpc-endpoint-host = "tapyrus1"
rpc-endpoint-port = 12381
rpc-endpoint-user = "user"
rpc-endpoint-pass = "pass"

[redis]
redis-host = "redis"
redis-port =  6379

[general]
round-duration = 20
log-quiet = false
log-level = "trace"
daemon = false
