[signer]
to-address = "19nBiVpPQ1rgmKkNaFpVktTTFWys4nwfYg"
public-key = "0313f2a73541e6d55a75a80a6da819885c6ed6e56ecff19f5e928c4ea202ca7c90"
federations-file = "/tmp/federations2.toml"

[rpc]
rpc-endpoint-host = "tapyrus2"
rpc-endpoint-port = 12381
rpc-endpoint-user = "user"
rpc-endpoint-pass = "pass"

[redis]
redis-host = "redis"
redis-port =  6379

[general]
round-duration = 20
log-quiet = false
log-level = "trace"
daemon = false
